
// Generated by Cadence Encounter(R) RTL Compiler RC14.13 - v14.10-s027_1

// Verification Directory fv/Fsm 

module Fsm(rst, clk, aim, motion_score, detail_score, make_motion,
     check_motion, make_detail, check_detail, make_video, motion_prmt,
     detail_prmt);
  input rst, clk;
  input [2:0] aim;
  input [7:0] motion_score, detail_score;
  output make_motion, check_motion, make_detail, check_detail,
       make_video;
  output [7:0] motion_prmt, detail_prmt;
  wire rst, clk;
  wire [2:0] aim;
  wire [7:0] motion_score, detail_score;
  wire make_motion, check_motion, make_detail, check_detail, make_video;
  wire [7:0] motion_prmt, detail_prmt;
  wire [31:0] state;
  wire [7:0] detail_target;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_225;
  wire n_226, n_227, n_228, n_229, n_230, n_232, n_233, n_277;
  wire n_278;
  DFFSNQ_X1 \state_reg[0] (.SN (1'b1), .CLK (clk), .D (n_233), .Q
       (state[0]));
  DFFSNQ_X1 \state_reg[1] (.SN (1'b1), .CLK (clk), .D (n_232), .Q
       (state[1]));
  NAND4_X1 g22360(.A1 (n_227), .A2 (n_202), .A3 (n_107), .A4 (n_74),
       .ZN (n_233));
  NAND3_X1 g22359(.A1 (n_230), .A2 (n_204), .A3 (n_82), .ZN (n_232));
  DFFSNQ_X1 \motion_prmt_reg[4] (.SN (1'b1), .CLK (clk), .D (n_278), .Q
       (motion_prmt[4]));
  DFFSNQ_X1 \motion_prmt_reg[7] (.SN (1'b1), .CLK (clk), .D (n_229), .Q
       (motion_prmt[7]));
  DFFSNQ_X1 \motion_prmt_reg[6] (.SN (1'b1), .CLK (clk), .D (n_228), .Q
       (motion_prmt[6]));
  DFFSNQ_X1 \motion_prmt_reg[5] (.SN (1'b1), .CLK (clk), .D (n_221), .Q
       (motion_prmt[5]));
  DFFSNQ_X1 \detail_prmt_reg[2] (.SN (1'b1), .CLK (clk), .D (n_220), .Q
       (detail_prmt[2]));
  DFFSNQ_X1 \detail_prmt_reg[6] (.SN (1'b1), .CLK (clk), .D (n_226), .Q
       (detail_prmt[6]));
  DFFRNQ_X1 \detail_target_reg[0] (.RN (1'b1), .CLK (clk), .D (n_222),
       .Q (detail_target[0]));
  DFFSNQ_X1 \detail_prmt_reg[4] (.SN (1'b1), .CLK (clk), .D (n_223), .Q
       (detail_prmt[4]));
  DFFSNQ_X1 \state_reg[2] (.SN (1'b1), .CLK (clk), .D (n_225), .Q
       (state[2]));
  DFFRNQ_X1 \detail_target_reg[4] (.RN (1'b1), .CLK (clk), .D (n_215),
       .Q (detail_target[4]));
  DFFSNQ_X1 \detail_prmt_reg[5] (.SN (1'b1), .CLK (clk), .D (n_214), .Q
       (detail_prmt[5]));
  DFFSNQ_X1 \detail_prmt_reg[7] (.SN (1'b1), .CLK (clk), .D (n_206), .Q
       (detail_prmt[7]));
  DFFSNQ_X1 \motion_prmt_reg[1] (.SN (1'b1), .CLK (clk), .D (n_210), .Q
       (motion_prmt[1]));
  DFFSNQ_X1 \motion_prmt_reg[3] (.SN (1'b1), .CLK (clk), .D (n_208), .Q
       (motion_prmt[3]));
  DFFSNQ_X1 \detail_prmt_reg[1] (.SN (1'b1), .CLK (clk), .D (n_211), .Q
       (detail_prmt[1]));
  DFFSNQ_X1 \motion_prmt_reg[2] (.SN (1'b1), .CLK (clk), .D (n_209), .Q
       (motion_prmt[2]));
  OAI21_X1 g22364(.A1 (n_188), .A2 (n_168), .B (n_139), .ZN (n_230));
  INV_X1 g22398(.I (n_218), .ZN (n_229));
  INV_X1 g22401(.I (n_217), .ZN (n_228));
  AOI22_X1 g22379(.A1 (n_203), .A2 (n_69), .B1 (n_136), .B2 (n_80), .ZN
       (n_227));
  DFFSNQ_X1 \detail_target_reg[1] (.SN (1'b1), .CLK (clk), .D (n_205),
       .Q (detail_target[1]));
  OAI22_X1 g22381(.A1 (n_177), .A2 (n_213), .B1 (n_40), .B2 (n_212),
       .ZN (n_226));
  DFFSNQ_X1 make_video_reg(.SN (1'b1), .CLK (clk), .D (n_193), .Q
       (make_video));
  DFFSNQ_X1 \detail_prmt_reg[3] (.SN (1'b1), .CLK (clk), .D (n_189), .Q
       (detail_prmt[3]));
  DFFSNQ_X1 \detail_prmt_reg[0] (.SN (1'b1), .CLK (clk), .D (n_190), .Q
       (detail_prmt[0]));
  OR2_X1 g22389(.A1 (n_198), .A2 (n_121), .Z (n_225));
  OAI21_X1 g22392(.A1 (n_195), .A2 (n_194), .B (n_196), .ZN (n_223));
  INV_X1 g22393(.I (n_207), .ZN (n_222));
  NAND2_X1 g22396(.A1 (n_192), .A2 (n_219), .ZN (n_221));
  NAND2_X1 g22397(.A1 (n_191), .A2 (n_219), .ZN (n_220));
  AOI22_X1 g22399(.A1 (n_175), .A2 (n_151), .B1 (n_216), .B2
       (motion_prmt[7]), .ZN (n_218));
  AOI22_X1 g22402(.A1 (n_216), .A2 (motion_prmt[6]), .B1 (n_173), .B2
       (n_108), .ZN (n_217));
  OAI22_X1 g22404(.A1 (n_72), .A2 (n_174), .B1 (n_183), .B2 (n_88), .ZN
       (n_215));
  OAI22_X1 g22406(.A1 (n_163), .A2 (n_213), .B1 (n_126), .B2 (n_212),
       .ZN (n_214));
  NAND2_X1 g22411(.A1 (n_170), .A2 (n_219), .ZN (n_211));
  OAI21_X1 g22414(.A1 (n_181), .A2 (n_180), .B (n_169), .ZN (n_210));
  NAND3_X1 g22417(.A1 (n_182), .A2 (n_150), .A3 (n_154), .ZN (n_209));
  OAI22_X1 g22425(.A1 (n_162), .A2 (n_172), .B1 (n_161), .B2 (n_171),
       .ZN (n_208));
  AOI22_X1 g22394(.A1 (n_165), .A2 (detail_target[0]), .B1 (n_185), .B2
       (n_59), .ZN (n_207));
  NAND2_X1 g22395(.A1 (n_176), .A2 (n_219), .ZN (n_206));
  INV_X1 g22377(.I (n_186), .ZN (n_205));
  OAI21_X1 g22405(.A1 (n_201), .A2 (n_197), .B (n_47), .ZN (n_204));
  DFFSNQ_X1 \detail_target_reg[5] (.SN (1'b1), .CLK (clk), .D (n_184),
       .Q (detail_target[5]));
  DFFSNQ_X1 \detail_target_reg[2] (.SN (1'b1), .CLK (clk), .D (n_167),
       .Q (detail_target[2]));
  DFFSNQ_X1 \motion_prmt_reg[0] (.SN (1'b1), .CLK (clk), .D (n_160), .Q
       (motion_prmt[0]));
  AND2_X1 g22408(.A1 (n_26), .A2 (n_187), .Z (n_203));
  NAND3_X1 g22409(.A1 (n_201), .A2 (n_178), .A3 (n_78), .ZN (n_202));
  NOR3_X1 g22413(.A1 (n_201), .A2 (n_197), .A3 (n_106), .ZN (n_198));
  AOI21_X1 g22416(.A1 (n_195), .A2 (n_194), .B (n_92), .ZN (n_196));
  INV_X1 g22418(.I (n_179), .ZN (n_193));
  XOR2_X1 g22423(.A1 (n_153), .A2 (motion_prmt[5]), .Z (n_192));
  XOR2_X1 g22422(.A1 (n_149), .A2 (detail_prmt[2]), .Z (n_191));
  OAI22_X1 g22424(.A1 (n_2), .A2 (n_212), .B1 (detail_prmt[0]), .B2
       (n_213), .ZN (n_190));
  OAI22_X1 g22426(.A1 (n_148), .A2 (n_213), .B1 (n_97), .B2 (n_212),
       .ZN (n_189));
  NOR3_X1 g22400(.A1 (n_187), .A2 (n_166), .A3 (n_84), .ZN (n_188));
  AOI22_X1 g22378(.A1 (n_157), .A2 (n_185), .B1 (detail_target[1]), .B2
       (n_141), .ZN (n_186));
  DFFSNQ_X1 check_motion_reg(.SN (1'b1), .CLK (clk), .D (n_164), .Q
       (check_motion));
  DFFSNQ_X1 make_motion_reg(.SN (1'b1), .CLK (clk), .D (n_155), .Q
       (make_motion));
  OAI21_X1 g22380(.A1 (n_144), .A2 (n_183), .B (n_122), .ZN (n_184));
  OR3_X1 g22484(.A1 (n_181), .A2 (n_180), .A3 (motion_prmt[2]), .Z
       (n_182));
  AOI22_X1 g22419(.A1 (make_video), .A2 (n_133), .B1 (n_87), .B2
       (n_178), .ZN (n_179));
  XOR2_X1 g22420(.A1 (n_127), .A2 (detail_prmt[6]), .Z (n_177));
  XOR2_X1 g22421(.A1 (n_134), .A2 (detail_prmt[7]), .Z (n_176));
  NAND2_X1 g22430(.A1 (n_156), .A2 (n_129), .ZN (n_175));
  AOI21_X1 g22435(.A1 (state[1]), .A2 (n_57), .B (n_159), .ZN (n_174));
  OAI21_X1 g22436(.A1 (n_173), .A2 (n_172), .B (n_171), .ZN (n_216));
  XOR2_X1 g22438(.A1 (n_146), .A2 (detail_prmt[1]), .Z (n_170));
  AOI22_X1 g22440(.A1 (n_116), .A2 (n_168), .B1 (n_137), .B2
       (motion_prmt[1]), .ZN (n_169));
  OAI21_X1 g22403(.A1 (n_135), .A2 (n_183), .B (n_147), .ZN (n_167));
  NOR2_X1 g22431(.A1 (n_166), .A2 (n_53), .ZN (n_187));
  NAND2_X1 g22432(.A1 (n_131), .A2 (n_73), .ZN (n_201));
  OAI21_X1 g22434(.A1 (n_111), .A2 (n_86), .B (n_158), .ZN (n_165));
  OAI22_X1 g22437(.A1 (n_7), .A2 (n_119), .B1 (n_18), .B2 (n_183), .ZN
       (n_164));
  XOR2_X1 g22439(.A1 (n_125), .A2 (detail_prmt[5]), .Z (n_163));
  XOR2_X1 g22464(.A1 (n_109), .A2 (n_161), .Z (n_162));
  OAI21_X1 g22456(.A1 (n_138), .A2 (n_171), .B (n_180), .ZN (n_160));
  DFFSNQ_X1 make_detail_reg(.SN (1'b1), .CLK (clk), .D (n_132), .Q
       (make_detail));
  DFFSNQ_X1 check_detail_reg(.SN (1'b1), .CLK (clk), .D (n_130), .Q
       (check_detail));
  INV_X1 g22478(.I (n_158), .ZN (n_159));
  OAI21_X1 g22415(.A1 (n_3), .A2 (n_142), .B (n_143), .ZN (n_157));
  NAND4_X1 g22485(.A1 (n_152), .A2 (n_0), .A3 (motion_prmt[5]), .A4
       (motion_prmt[6]), .ZN (n_156));
  INV_X1 g22488(.I (n_140), .ZN (n_155));
  NAND2_X1 g22446(.A1 (motion_prmt[2]), .A2 (n_113), .ZN (n_154));
  OAI21_X1 g22450(.A1 (n_128), .A2 (motion_prmt[3]), .B (n_118), .ZN
       (n_199));
  OAI21_X1 g22451(.A1 (n_152), .A2 (n_94), .B (n_151), .ZN (n_153));
  NOR2_X1 g22452(.A1 (n_110), .A2 (n_213), .ZN (n_195));
  NAND3_X1 g22453(.A1 (n_68), .A2 (motion_prmt[0]), .A3 (n_151), .ZN
       (n_150));
  AOI21_X1 g22457(.A1 (n_101), .A2 (state[3]), .B (n_115), .ZN (n_212));
  NAND3_X1 g22459(.A1 (n_20), .A2 (n_35), .A3 (n_145), .ZN (n_149));
  XOR2_X1 g22462(.A1 (n_85), .A2 (detail_prmt[3]), .Z (n_148));
  DFFSNQ_X1 \state_reg[3] (.SN (1'b1), .CLK (clk), .D (n_91), .Q
       (state[3]));
  NAND2_X1 g22467(.A1 (detail_target[2]), .A2 (n_219), .ZN (n_147));
  NAND2_X1 g22471(.A1 (n_30), .A2 (n_145), .ZN (n_146));
  AOI21_X1 g22410(.A1 (detail_target[5]), .A2 (n_143), .B (n_142), .ZN
       (n_144));
  OAI22_X1 g22477(.A1 (n_93), .A2 (n_65), .B1 (n_117), .B2 (n_50), .ZN
       (n_173));
  NOR3_X1 g22479(.A1 (n_90), .A2 (state[0]), .A3 (n_141), .ZN (n_158));
  AOI22_X1 g22489(.A1 (n_139), .A2 (n_168), .B1 (make_motion), .B2
       (n_64), .ZN (n_140));
  NAND2_X1 g22502(.A1 (n_138), .A2 (n_151), .ZN (n_180));
  OAI21_X1 g22513(.A1 (n_136), .A2 (n_138), .B (n_151), .ZN (n_137));
  NOR2_X1 g22433(.A1 (n_142), .A2 (n_56), .ZN (n_135));
  AOI21_X1 g22442(.A1 (n_83), .A2 (motion_score[5]), .B
       (motion_score[7]), .ZN (n_166));
  NOR2_X1 g22443(.A1 (n_102), .A2 (n_100), .ZN (n_134));
  NAND2_X1 g22445(.A1 (n_54), .A2 (n_114), .ZN (n_133));
  OAI21_X1 g22448(.A1 (n_89), .A2 (n_183), .B (n_105), .ZN (n_132));
  OAI21_X1 g22449(.A1 (n_61), .A2 (n_51), .B (n_95), .ZN (n_131));
  OAI21_X1 g22460(.A1 (n_104), .A2 (n_120), .B (n_103), .ZN (n_130));
  AOI22_X1 g22461(.A1 (n_128), .A2 (n_79), .B1 (n_33), .B2
       (motion_prmt[7]), .ZN (n_129));
  OAI22_X1 g22463(.A1 (n_123), .A2 (detail_prmt[5]), .B1 (n_124), .B2
       (n_126), .ZN (n_127));
  NOR2_X1 g22468(.A1 (n_124), .A2 (n_123), .ZN (n_125));
  NAND2_X1 g22470(.A1 (detail_target[5]), .A2 (n_141), .ZN (n_122));
  OAI21_X1 g22474(.A1 (n_39), .A2 (n_120), .B (n_70), .ZN (n_121));
  AOI21_X1 g22475(.A1 (n_112), .A2 (state[1]), .B (n_141), .ZN (n_119));
  AOI21_X1 g22476(.A1 (n_117), .A2 (motion_prmt[3]), .B (n_172), .ZN
       (n_118));
  OAI21_X1 g22480(.A1 (n_67), .A2 (motion_prmt[0]), .B (n_76), .ZN
       (n_116));
  INV_X1 g22482(.I (n_114), .ZN (n_115));
  NAND4_X1 g22487(.A1 (n_112), .A2 (n_36), .A3 (n_111), .A4 (n_45), .ZN
       (n_113));
  INV_X1 g22490(.I (n_99), .ZN (n_110));
  NAND2_X1 g22495(.A1 (n_117), .A2 (n_66), .ZN (n_109));
  NOR2_X1 g22499(.A1 (motion_prmt[6]), .A2 (n_172), .ZN (n_108));
  OR2_X1 g22507(.A1 (n_111), .A2 (n_106), .Z (n_107));
  OAI21_X1 g22472(.A1 (n_104), .A2 (rst), .B (make_detail), .ZN
       (n_105));
  OAI21_X1 g22473(.A1 (n_21), .A2 (n_81), .B (check_detail), .ZN
       (n_103));
  NOR4_X1 g22481(.A1 (n_42), .A2 (n_96), .A3 (n_101), .A4 (n_120), .ZN
       (n_102));
  AOI21_X1 g22483(.A1 (n_104), .A2 (n_22), .B (rst), .ZN (n_114));
  NOR4_X1 g22486(.A1 (n_38), .A2 (n_98), .A3 (n_101), .A4 (n_120), .ZN
       (n_100));
  AOI22_X1 g22491(.A1 (n_98), .A2 (n_97), .B1 (n_96), .B2
       (detail_prmt[3]), .ZN (n_99));
  NAND4_X1 g22492(.A1 (n_77), .A2 (n_60), .A3 (n_95), .A4 (n_16), .ZN
       (n_197));
  NOR2_X1 g22496(.A1 (n_117), .A2 (n_13), .ZN (n_152));
  NOR2_X1 g22497(.A1 (n_93), .A2 (n_49), .ZN (n_94));
  INV_X1 g22500(.I (n_92), .ZN (n_219));
  AND2_X1 g22508(.A1 (n_112), .A2 (n_168), .Z (n_171));
  OAI22_X1 g22520(.A1 (n_90), .A2 (n_120), .B1 (n_89), .B2 (n_29), .ZN
       (n_91));
  INV_X1 g22528(.I (n_183), .ZN (n_185));
  INV_X1 g22533(.I (n_172), .ZN (n_151));
  INV_X1 g22538(.I (n_213), .ZN (n_145));
  NAND2_X1 g22447(.A1 (n_87), .A2 (n_86), .ZN (n_88));
  NOR4_X1 g22458(.A1 (n_58), .A2 (n_12), .A3 (n_44), .A4 (aim[0]), .ZN
       (n_142));
  NOR2_X1 g22493(.A1 (n_96), .A2 (n_41), .ZN (n_124));
  NOR2_X1 g22494(.A1 (n_98), .A2 (n_24), .ZN (n_123));
  AND2_X1 g22498(.A1 (n_98), .A2 (n_96), .Z (n_85));
  NOR2_X1 g22501(.A1 (n_104), .A2 (n_84), .ZN (n_92));
  INV_X1 g22503(.I (n_55), .ZN (n_83));
  OR2_X1 g22506(.A1 (n_111), .A2 (n_81), .Z (n_82));
  OAI21_X1 g22509(.A1 (n_75), .A2 (state[1]), .B (n_80), .ZN (n_141));
  NOR4_X1 g22510(.A1 (n_48), .A2 (motion_prmt[5]), .A3
       (motion_prmt[6]), .A4 (motion_prmt[7]), .ZN (n_79));
  OR2_X1 g22511(.A1 (n_77), .A2 (n_71), .Z (n_78));
  AOI21_X1 g22514(.A1 (n_46), .A2 (n_28), .B (n_75), .ZN (n_76));
  OAI21_X1 g22515(.A1 (n_75), .A2 (n_63), .B (n_37), .ZN (n_74));
  AOI21_X1 g22516(.A1 (n_72), .A2 (detail_score[4]), .B (n_71), .ZN
       (n_73));
  AOI22_X1 g22518(.A1 (n_87), .A2 (n_69), .B1 (n_90), .B2 (n_17), .ZN
       (n_70));
  OAI22_X1 g22519(.A1 (n_67), .A2 (motion_prmt[2]), .B1 (n_27), .B2
       (motion_prmt[1]), .ZN (n_68));
  INV_X1 g22522(.I (n_128), .ZN (n_66));
  NAND2_X1 g22524(.A1 (n_31), .A2 (n_32), .ZN (n_65));
  NAND2_X1 g22527(.A1 (n_75), .A2 (n_80), .ZN (n_64));
  NAND2_X1 g22529(.A1 (state[1]), .A2 (n_80), .ZN (n_183));
  NAND2_X1 g22534(.A1 (n_63), .A2 (n_80), .ZN (n_172));
  NAND2_X1 g22536(.A1 (state[0]), .A2 (n_62), .ZN (n_106));
  NAND2_X1 g22539(.A1 (n_90), .A2 (n_62), .ZN (n_213));
  AND3_X1 g22547(.A1 (n_15), .A2 (n_60), .A3 (detail_score[0]), .Z
       (n_61));
  NOR2_X1 g22444(.A1 (n_58), .A2 (n_57), .ZN (n_59));
  INV_X1 g22454(.I (n_143), .ZN (n_56));
  NOR3_X1 g22466(.A1 (n_8), .A2 (n_43), .A3 (aim[1]), .ZN (n_86));
  OAI21_X1 g22504(.A1 (n_52), .A2 (motion_score[2]), .B
       (motion_score[6]), .ZN (n_55));
  OAI21_X1 g22505(.A1 (n_89), .A2 (state[1]), .B (state[3]), .ZN
       (n_54));
  NOR4_X1 g22512(.A1 (n_52), .A2 (motion_score[7]), .A3
       (motion_score[1]), .A4 (motion_score[0]), .ZN (n_53));
  OAI22_X1 g22517(.A1 (detail_target[2]), .A2 (n_9), .B1
       (detail_target[1]), .B2 (n_25), .ZN (n_51));
  NAND2_X1 g22521(.A1 (n_14), .A2 (motion_prmt[5]), .ZN (n_50));
  NOR2_X1 g22523(.A1 (n_49), .A2 (n_181), .ZN (n_128));
  OR2_X1 g22525(.A1 (n_48), .A2 (n_181), .Z (n_93));
  NOR2_X1 g22531(.A1 (state[1]), .A2 (n_120), .ZN (n_178));
  NOR2_X1 g22532(.A1 (state[1]), .A2 (n_84), .ZN (n_168));
  NOR2_X1 g22537(.A1 (n_112), .A2 (n_120), .ZN (n_47));
  NAND3_X1 g22542(.A1 (n_46), .A2 (motion_prmt[2]), .A3
       (motion_prmt[1]), .ZN (n_117));
  AOI21_X1 g22543(.A1 (state[0]), .A2 (motion_prmt[1]), .B (n_84), .ZN
       (n_45));
  NAND3_X1 g22455(.A1 (n_87), .A2 (n_44), .A3 (aim[0]), .ZN (n_143));
  NAND2_X1 g22469(.A1 (n_43), .A2 (aim[1]), .ZN (n_57));
  INV_X1 g22592(.I (n_87), .ZN (n_58));
  INV_X1 g22587(.I (n_90), .ZN (n_101));
  OR3_X1 g22540(.A1 (n_41), .A2 (n_126), .A3 (n_40), .Z (n_42));
  INV_X1 g22580(.I (n_120), .ZN (n_62));
  NAND2_X1 g22526(.A1 (n_39), .A2 (n_136), .ZN (n_104));
  NAND2_X1 g22530(.A1 (detail_target[2]), .A2 (n_11), .ZN (n_95));
  NAND3_X1 g22541(.A1 (n_23), .A2 (n_40), .A3 (n_126), .ZN (n_38));
  OAI21_X1 g22544(.A1 (n_136), .A2 (state[3]), .B (n_37), .ZN (n_81));
  NAND3_X1 g22545(.A1 (n_136), .A2 (n_138), .A3 (state[2]), .ZN (n_36));
  OAI21_X1 g22546(.A1 (detail_target[5]), .A2 (n_34), .B (n_10), .ZN
       (n_71));
  NAND4_X1 g22548(.A1 (n_136), .A2 (detail_prmt[2]), .A3
       (detail_prmt[1]), .A4 (detail_prmt[0]), .ZN (n_96));
  OR4_X1 g22549(.A1 (n_136), .A2 (detail_prmt[0]), .A3
       (detail_prmt[1]), .A4 (detail_prmt[2]), .Z (n_98));
  AOI22_X1 g22550(.A1 (n_4), .A2 (detail_prmt[0]), .B1 (state[0]), .B2
       (detail_prmt[1]), .ZN (n_35));
  AOI22_X1 g22551(.A1 (detail_target[4]), .A2 (n_6), .B1
       (detail_target[5]), .B2 (n_34), .ZN (n_77));
  OAI22_X1 g22552(.A1 (n_32), .A2 (motion_prmt[6]), .B1 (n_5), .B2
       (motion_prmt[5]), .ZN (n_33));
  INV_X1 g22556(.I (n_49), .ZN (n_31));
  AOI21_X1 g22535(.A1 (state[0]), .A2 (detail_prmt[0]), .B (n_19), .ZN
       (n_30));
  INV_X1 g22571(.I (n_84), .ZN (n_80));
  INV_X1 g22583(.I (n_69), .ZN (n_29));
  INV_X1 g22590(.I (n_112), .ZN (n_139));
  NOR2_X1 g22589(.A1 (n_138), .A2 (state[0]), .ZN (n_46));
  NAND2_X1 g22581(.A1 (state[3]), .A2 (n_37), .ZN (n_120));
  NOR2_X1 g22584(.A1 (n_111), .A2 (rst), .ZN (n_69));
  NAND2_X1 g22585(.A1 (n_28), .A2 (state[0]), .ZN (n_181));
  NAND2_X1 g22586(.A1 (n_136), .A2 (motion_prmt[1]), .ZN (n_67));
  NAND2_X1 g22557(.A1 (n_138), .A2 (n_27), .ZN (n_49));
  NOR2_X1 g22593(.A1 (state[0]), .A2 (n_26), .ZN (n_87));
  NAND2_X1 g22554(.A1 (detail_target[1]), .A2 (n_25), .ZN (n_60));
  NOR2_X1 g22588(.A1 (n_111), .A2 (state[2]), .ZN (n_90));
  NAND2_X1 g22567(.A1 (n_161), .A2 (n_1), .ZN (n_48));
  INV_X1 g22568(.I (n_23), .ZN (n_24));
  NAND2_X1 g22572(.A1 (n_22), .A2 (n_37), .ZN (n_84));
  INV_X1 g22573(.I (n_39), .ZN (n_21));
  INV_X1 g22575(.I (n_19), .ZN (n_20));
  INV_X1 g22578(.I (n_75), .ZN (n_18));
  NOR2_X1 g22582(.A1 (n_136), .A2 (rst), .ZN (n_17));
  NAND2_X1 g22591(.A1 (state[0]), .A2 (n_26), .ZN (n_112));
  OR2_X1 g22553(.A1 (n_15), .A2 (detail_score[0]), .Z (n_16));
  NOR2_X1 g22594(.A1 (n_26), .A2 (state[1]), .ZN (n_63));
  INV_X1 g22558(.I (n_13), .ZN (n_14));
  AND2_X1 g22566(.A1 (aim[2]), .A2 (aim[1]), .Z (n_12));
  NOR2_X1 g22569(.A1 (detail_prmt[4]), .A2 (detail_prmt[3]), .ZN
       (n_23));
  NAND2_X1 g22559(.A1 (motion_prmt[3]), .A2 (motion_prmt[4]), .ZN
       (n_13));
  NAND2_X1 g22563(.A1 (detail_score[3]), .A2 (detail_score[2]), .ZN
       (n_11));
  NOR2_X1 g22579(.A1 (state[0]), .A2 (state[2]), .ZN (n_75));
  NAND2_X1 g22577(.A1 (state[0]), .A2 (state[2]), .ZN (n_89));
  NOR2_X1 g22576(.A1 (state[0]), .A2 (detail_prmt[0]), .ZN (n_19));
  NOR2_X1 g22561(.A1 (aim[2]), .A2 (aim[0]), .ZN (n_43));
  NOR2_X1 g22562(.A1 (aim[2]), .A2 (aim[1]), .ZN (n_44));
  NOR2_X1 g22564(.A1 (detail_score[7]), .A2 (detail_score[6]), .ZN
       (n_10));
  NOR2_X1 g22565(.A1 (detail_score[3]), .A2 (detail_score[2]), .ZN
       (n_9));
  OR2_X1 g22570(.A1 (motion_score[4]), .A2 (motion_score[3]), .Z
       (n_52));
  NOR2_X1 g22574(.A1 (state[2]), .A2 (state[1]), .ZN (n_39));
  NAND2_X1 g22555(.A1 (detail_prmt[3]), .A2 (detail_prmt[4]), .ZN
       (n_41));
  AND2_X1 g22560(.A1 (aim[2]), .A2 (aim[0]), .Z (n_8));
  INV_X1 g22610(.I (check_motion), .ZN (n_7));
  INV_X1 g22618(.I (detail_score[5]), .ZN (n_34));
  INV_X1 g22615(.I (motion_prmt[0]), .ZN (n_138));
  INV_X1 g22596(.I (motion_prmt[1]), .ZN (n_28));
  INV_X1 g22619(.I (detail_score[1]), .ZN (n_25));
  INV_X1 g22602(.I (detail_prmt[4]), .ZN (n_194));
  INV_X1 g22614(.I (motion_prmt[2]), .ZN (n_27));
  INV_X1 g22620(.I (detail_score[4]), .ZN (n_6));
  INV_X1 g22603(.I (detail_target[4]), .ZN (n_72));
  INV_X1 g22598(.I (motion_prmt[6]), .ZN (n_5));
  INV_X1 g22605(.I (state[2]), .ZN (n_26));
  INV_X1 g22595(.I (detail_prmt[3]), .ZN (n_97));
  INV_X1 g22612(.I (detail_prmt[1]), .ZN (n_4));
  INV_X1 g22611(.I (state[1]), .ZN (n_111));
  INV_X1 g22606(.I (motion_prmt[5]), .ZN (n_32));
  INV_X1 g22604(.I (motion_prmt[3]), .ZN (n_161));
  INV_X1 g22609(.I (detail_target[0]), .ZN (n_15));
  INV_X1 g22607(.I (state[3]), .ZN (n_22));
  INV_X1 g22613(.I (detail_target[1]), .ZN (n_3));
  INV_X1 g22608(.I (detail_prmt[5]), .ZN (n_126));
  INV_X1 g22617(.I (rst), .ZN (n_37));
  INV_X1 g22616(.I (detail_prmt[0]), .ZN (n_2));
  INV_X1 g22597(.I (state[0]), .ZN (n_136));
  INV_X1 g22600(.I (motion_prmt[4]), .ZN (n_1));
  INV_X1 g22599(.I (motion_prmt[7]), .ZN (n_0));
  INV_X1 g22601(.I (detail_prmt[6]), .ZN (n_40));
  NAND2_X1 g2(.A1 (n_277), .A2 (n_219), .ZN (n_278));
  XOR2_X1 g3(.A1 (n_199), .A2 (motion_prmt[4]), .Z (n_277));
endmodule

